builds:
  - id: wuzapi
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
    targets:
      - linux_amd64
      - linux_arm64
      - linux_386
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64
